### ISSUE TITLE
Avoid putting secrets to ETCD

### ISSUE THREAD

**Issue by max-lobur** [external-secrets/kubernetes-external-secrets#46]
Current implementation creates an etcd object with base64 encoded secret, which may potentially leak later. 

Allow to put secrets to a volume, e.g. add a mutation webhook which adds an initContainer, which fetches & writes secrets to a volume shared with a container.

Pros: 
 - no secrets in etcd
 - iam role can be granularly assigned to each initContainer (based on namespace annotation for example) when using https://github.com/uswitch/kiam , no need to give access to all secrets to the controller

**Comment by silasbw** [comment]
Hey @max-lobur, how much does using [encryption at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/) mitigate your concerns around etcd storage?

**Comment by max-lobur** [comment]
- It's just about hacked/dumped eventually. 
- Depending of https://coreos.com/etcd/docs/latest/op-guide/configuration.html#--auto-compaction-retention etcd even can have values of deleted secrets. 
- Etcd (and k8s) backups must be treated carefully because now they contain sensitive data.

**Comment by silasbw** [comment]
Thanks, that's helpful for understanding the potential priority of an addition like this.

**Comment by silasbw** [comment]
I did some planning for this and some initial implementation work:

- [x] [POC Init Container example](https://github.com/godaddy/kubernetes-external-secrets/pull/77)
- [ ] [Issue to discuss / plan what the "API" is](https://github.com/godaddy/kubernetes-external-secrets/issues/78)
- [ ] [Implementation work to get the admission webhook server up](https://github.com/godaddy/kubernetes-external-secrets/issues/79)
- [ ] [Tie it all together end-to-end](https://github.com/godaddy/kubernetes-external-secrets/issues/81)

Feel free to jump in a give feedback (especially on https://github.com/godaddy/kubernetes-external-secrets/issues/78) or help out with coding :stuck_out_tongue:

**Comment by gazal-k** [comment]
> * It's just about etcd hacked/dumped eventually.
> * Depending of https://coreos.com/etcd/docs/latest/op-guide/configuration.html#--auto-compaction-retention etcd even can have values of deleted secrets.
> * Etcd (and k8s) backups must be treated carefully because now they contain secrets.

If etcd is encrypted does all of this still matter? My understanding is that EKS does encrypt etcd; https://github.com/aws/containers-roadmap/issues/263#issuecomment-540920847. I haven't verified, but I assume EKS uses KMS to encrypt etcd.

**Comment by max-lobur** [comment]
Yes it matters because it's unencrypted in etcd api / k8s api.

Implementation example https://github.com/cruise-automation/daytona
(fetching to in-mem volume)

**Comment by gazal-k** [comment]
Can't K8s API access be controlled using rbac?

I understand that there are integrations for vault that don't store secrets in etcd. This one: https://github.com/banzaicloud/bank-vaults uses a mutating admission webhook.

I'm not suggesting that they're all getting it wrong. I'm just trying to fully understand it if I can.

**Comment by kuuji** [comment]
> Yes it matters because it's unencrypted in etcd api / k8s api.
> 
> Implementation example https://github.com/cruise-automation/daytona
> (fetching to in-mem volume)

You can encrypt the actual value in etcd on EKS this way  -> https://aws.amazon.com/blogs/containers/using-eks-encryption-provider-support-for-defense-in-depth/

Note that this is not at rest, the kms encryption happens at the k8s api level, before it's stored in etcd.

I believe other k8s implementations should support envelope encryption with a CMK as well.

**Comment by IamViditAgarwal** [comment]
Hi,
Any update on this, when it will come live. Waiting to see it
